name: la_bodeguita
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # ğŸ”¹ Firebase (versiones compatibles entre sÃ­)
  firebase_core: ^4.2.1
  cloud_firestore: ^6.1.0

  # ğŸ”¹ Animaciones y utilidades de UI
  animate_do: ^4.2.0        # Para animaciones suaves
  badges: ^3.1.2            # Para mostrar el nÃºmero del carrito
  pull_to_refresh: ^2.0.0   # (opcional, si usas 'jalar para refrescar')
  firebase_auth: ^6.1.2

  # ğŸ”¹ Mapas y ubicaciÃ³n
  google_maps_flutter: ^2.13.1
  geolocator: ^14.0.2
  http: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/bodeguita_icon.png
    - assets/persona_icon.png
